### ISSUE TITLE
Popup Refactor (Epic PR to Main) Review TODO List

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay-add-on#475]
Thanks for the reviews from @codemist, @lloan and @Vinnl. I generated a lengthy TODO list in response to the review. Filing it here to make it easier to track against the BIG pr, even though I'll be committing directly to the [`mpp-1714-staging` branch](https://github.com/mozilla/fx-private-relay-add-on/tree/mpp-1714-staging). 

# TODO: 

## Global/features:
- [ ] Analytics review
- [ ] News item count

### [src/popup.html](https://github.com/mozilla/fx-private-relay-add-on/blob/mpp-1714-staging/src/popup.html)
- [x] Localize Navigation items
- [ ] Update navigation elements to `<button>` instead of `<a>` 
- [ ] Add alt-tag to Close button (`.fx-relay-masks-error-message-icon`)
- [ ] Comment on dynamically populated markup in HTML
- [ ] Custom elements `<content>`, `<panel>`, etc should all contain a hyphen 

### [src/js/popup/popup.js](https://github.com/mozilla/fx-private-relay-add-on/blob/mpp-1714-staging/src/js/popup/popup.js)
- [ ] Question: Use local storage for state mgmt for persistent items (newsItemCount?)
- [ ] State object: remove unused data 
- [ ] Use lloan suggestion `f ([400,409].includes(newRelayAddressResponse.status)) {`
- [ ] masks.custom.init: Remove commented code 
- [ ] Use lloan suggestion: `matchesSearchFilter`
- [ ] Check on `TODO: Add toggle button back`
- [ ] Question about destructing: `const { emailsForwardedVal } = await ...
- [ ] Use lloan suggestion: `domainList === null` (or Kaitlyn ?? operator)
- [ ] Fix line-breaks: panel.init function
- [ ] Consider re-ordering `noMasksPanelCreated` panel to show by default
- [ ] `isPremiumSubdomainSet` is defined and used multiple times
- [ ] Remove extra line-breaks in `setRemainingMaskCount`
- [ ] Rename `storyData` to something more legible. 
- [ ] News item issue: `isPhoneMaskingAvailable` and `logicCheck` may be unnecessary / duplicate 

### [src/js/background/background.js](https://github.com/mozilla/fx-private-relay-add-on/blob/mpp-1714-staging/src/js/background/background.js)
- [ ] Remove console log
- [ ] Add comment on `apiBody.used_on = description + ",";`
- [ ] Investigate FIXME
- [ ] Investigate `// TODO: Update the domain attribute to be "label"`
- [ ] Add comment for `const localRelayAddresses = Object.keys(localStorageRelayAddresses).`
- [ ] Use lloan suggestion: `return { status: 402 };`
- [ ] Add comment for `return { status: 402 };`

### [src/css/global.css](https://github.com/mozilla/fx-private-relay-add-on/blob/mpp-1714-staging/src/css/global.css)
- [ ] font / font-size rev. Revert 

### [src/css/popup.css](https://github.com/mozilla/fx-private-relay-add-on/blob/mpp-1714-staging/src/css/popup.css)
- [ ] Double width attributes `.fx-relay-panel-header-btn-back img`
- [ ] `right` value should be variable `.fx-relay-settings-toggle::after` 
- [ ] Add `z-index` comment `fx-relay-panel-custom-mask-promo-blocking-tooltip`
