### ISSUE TITLE
Improve addon popup functionality

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/fx-private-relay-add-on#75]
**Request**

Explore how we might add more value to the Relay Add-on. 
Address the "dead-end" experienced with the "5/5" state.

- [x] Individual evaluation of the experience to highlight issues and opportunities
- [x] Review and collate reported issues from Beta
- [x] Sketchwork for rapid solution visuals
- [x] Experience flow 
- [x] Share with teams for async critique
- [x] Explore addon visuals depicting varying amounts of functionality 
- [ ] Complete research kickoff document
- [ ] Produce refined prototypes for usability testing 
- [ ] Set up usability tests
- [ ] Design creation
- [ ] Prototype (Figma) creation 

**Timeline and priority (if applicable)**

- By 9/17: Sketch and experience flow delivered for feedback
- By 10/7: complete research document and launch study

**Linked issues**

- 

**Additional context**

- [Issue audit and research opportunities](https://docs.google.com/document/d/1Y8ZYn1nF0z1wbIVNRM9yFsRZzTeKolCEWpeOl5AGwiY/edit?usp=sharing)
- [Firefox Relay Mana](https://mana.mozilla.org/wiki/display/FIREFOX/Firefox+Relay)

---

### Original post:

We should consider adding some of the dashboard functionality back into the addon popup

Initial thoughts are that we should:
1.) Add a new "default" panel that reproduces some dashboard functionality, or at least just lets the user create new aliases.
2.) Consider moving the existing panels into something like an onboarding flow. 
3.) Consider revamping or removing the "High Five!" panel

Something to keep in mind: 
- To preserve the privacy benefit of using aliases, we actually don't want to encourage alias re-use

Related to: mozilla/fx-private-relay-add-on#62 , mozilla/fx-private-relay-add-on#64 , mozilla/fx-private-relay-add-on#58 , mozilla/fx-private-relay-add-on#71
